@extends('layouts.front')
@section('content')
@include('front-end.components.carousel')
@include('front-end.components.section1')
@include('front-end.components.testimonial')
@include('front-end.components.section2')
@include('front-end.components.section3')
@include('front-end.components.contact')
@endsection
