@extends('layouts.front')
@section('content')
@include('front-end.components.currentpage')
@include('front-end.components.services_services')
@include('front-end.components.services_phone')
@include('front-end.components.services_blog')
@include('front-end.components.newsletter')
@include('front-end.components.contact')
@endsection
